spring.application.name=eFacturador
# Configuraci?n de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:54321/db_sigme
spring.datasource.username=sigme
spring.datasource.password=Epdlmede2*
spring.datasource.driver-class-name=org.postgresql.Driver
# Dialecto de Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Estrategia de actualizaci?n del esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update
# Mostrar consultas SQL en la consola (opcional)
spring.jpa.show-sql=true
# Formatear las consultas SQL en la consola (opcional)
spring.jpa.properties.hibernate.format_sql=true
# Mostrar los valores de los par?metros bind
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.braintech.eFacturador.dao.inventario=DEBUG
jwt.secret=${JWT_SECRET}

