version: "3.9"
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: sigme
      POSTGRES_PASSWORD: Epdlmede2*
      POSTGRES_DB: db_sigme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
