//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package com.braintech.eFacturador.facturacionelectronica.models;

public enum TipoAjusteType {
  D,
  R;

  public String value() {
    return name();
  }

  public static TipoAjusteType fromValue(String v) {
    return valueOf(v);
  }
}
